### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by max3903** [akretion/storage-deprecated-moved-to-oca#38]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] storage_backend by @bodedra
- [ ] storage_backend_sftp by @bodedra
- [ ] storage_backend_s3
- [ ] storage_file
- [ ] storage_image
- [ ] storage_image_category_pos
- [ ] storage_image_product
- [ ] storage_image_product_pos
- [ ] storage_thumbnail

**Comment by max3903** [comment]
#40
