### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by sebastienbeau** [akretion/storage-deprecated-moved-to-oca#40]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] storage_backend
- [ ] storage_backend_s3
- [ ] storage_backend_sftp
- [ ] storage_file
- [ ] storage_image
- [ ] storage_image_category_pos
- [ ] storage_image_product
- [ ] storage_image_product_pos
- [ ] storage_thumbnail

**Comment by max3903** [comment]
@bodedra will migrate storage_backend and storage_backend_sftp.

**Comment by bodedra** [comment]
storage_backend https://github.com/akretion/storage/pull/41

**Comment by bodedra** [comment]
storage_backend_sftp #42
