### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by rousseldenis** [akretion/storage-deprecated-moved-to-oca#67]
# Todo
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate
* [ ]  storage_backend - By @rousseldenis - #68 
* [ ]  storage_backend_s3
* [ ]  storage_backend_sftp
* [ ]  storage_file - By @rousseldenis -  #69 
* [ ]  storage_image - By @rousseldenis
* [ ]  storage_image_category_pos
* [ ]  storage_image_product
* [ ]  storage_image_product_pos
* [ ]  storage_thumbnail - By @rousseldenis - #70

**Comment by rousseldenis** [comment]
@sebastienbeau @bguillot I begin by storage_backend. But as keychain is deprecated and as we did in https://github.com/shopinvader/odoo-shopinvader/pull/337, I set fields as normal ones.
